server:
  port: 9090

spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}
  application:
    name: Event Sourcing with Axon, Kafka and MongoDB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: readDB

axon:
  serializer:
    general: jackson
    messages: jackson
    events: jackson
  kafka:
    bootstrap-servers: localhost:9092
    client-id: accounts
    default-topic: accounts
    properties:
      security.protocol: PLAINTEXT
    publisher:
      confirmation-mode: transactional
    producer:
      retries: 5
      event-processor-mode: subscribing
    fetcher:
      poll-timeout: 3000
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 3000
      event-processor-mode: tracking
